config/routes.rb
Ehr::Application.routes.draw do

  resources :patients do
    resources :addresses
    resources :contacts
    resources :allergies
    resources :appointments do
      resources :progress_notes
      resources :initial_evaluations
      resources :prescriptions
      member do
        get 'cancel'
        get 'uncancel'
      end
    end
    resources :patient_doctor_relations
    collection do 
      get 'ethnicities', format: :json
      get 'occupations', format: :json
      get 'marital_statuses', format: :json
    end
  end

  resources :calendars, only: [ :index ]

  devise_for :users

  root 'home#index'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  extend ScopedSearch

  belongs_to :patient
  belongs_to :user
  belongs_to :appointment

  validates :patient_id, :user_id, presence: true

  scope :by_user, ->(user_id) { where(user_id: user_id) if user_id }
  scope :by_patient, ->(patient_id) { where(patient_id: patient_id) if patient_id }
  scope :by_allowed_user, ->(user) { allowed_user_lambda.call(user) }
  scope :by_created_at, ->(stdt, endt) { date_range_lambda.call(stdt, endt) }
  scope :by_search, ->(q) { fields_like_lambda.call(q, :prescription) }

  def summary 
    arr = []
    arr << appointment.start_at.strftime('%m/%d/%Y') if appointment
    arr << self.medication_status
    arr << self.prescription
    arr.join(' ')
  end

  def date
    self.appointment ? self.apppointment.start_at : self.created_at
  end

  def date_str
    self.date.strftime('%m/%d/%Y')
  end

end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_prescription, only: [:show]
  before_action :set_writable_prescription, only: [:edit, :update, :destroy]
  before_action :set_patient
  before_action :set_appointment

  def index
    @presenter = PrescriptionsPresenter.new(current_user, params)
  end

  def show
  end

  def new
    @prescription = Prescription.new
    @prescription.patient = @patient
    @prescription.user = current_user
  end

  def edit
  end

  def create

    @prescription = Prescription.new(prescription_params)
    @prescription.patient = @patient
    @prescription.user = current_user
    @prescription.appointment = @appointment

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @patient, 
          notice: 'Prescription was successfully created.' }
        format.json { render action: 'show', 
          status: :created, 
          location: @prescription }
      else
        format.html { render action: 'new' }
        format.json { render json: @prescription.errors, 
          status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @patient, 
          notice: 'Prescription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prescription.errors, 
          status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to patient_url(@patient) }
      format.json { head :no_content }
    end
  end

  private

  def set_prescription
    @prescription = Prescription.by_allowed_user(current_user).find(params[:id])
  end

  def set_writable_prescription
    @prescription = current_user.prescriptions.find(params[:id])
  end

  def prescription_params
    params.require(:prescription).permit(:medication_status, :prescription, :notes)
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper

  def prescription p
    content_tag(:span, class: "prescription-#{ p.medication_status }") do 
      if p.appointment
        "#{ p.appointment.date_str }: #{ p.prescription }"
      else
        "#{ p.created_at.strftime('%m/%d/%Y') }: #{ p.prescription }"
      end
    end
  end

  MEDICATION_STATUS_TO_LABEL = {
    MedicationStatus::PRESCRIBED => 'label-success',
    MedicationStatus::CEASED => '',
    MedicationStatus::INCREASED => 'label-info',
    MedicationStatus::DECREASED => 'label-info'
  }

  def prescription_span p
    content_tag :span, 
        p.medication_status, 
        class: "label #{ MEDICATION_STATUS_TO_LABEL[p.medication_status] }"
  end
end

app/views/prescriptions/_form.html.erb
  <div class="control-group">
    <%= f.label :prescription, class: 'control-label' %>
    <div class="controls">
      <div class="span3">
        <%= f.select :medication_status, MedicationStatus::ALL, {}, class: 'input-block-level' %>
      </div>
      <div class="span9">
        <%= f.text_field :prescription, class: 'input-block-level' %>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :notes, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :notes, class: 'input-block-level' %>
    </div>
  </div>

app/views/prescriptions/_module.html.erb
<div class="module-block">
  <h5>Medication Changes</h5>
  <% unless @patient.prescriptions.empty? %>
    <ul>
      <% @patient.prescriptions_in_order.each do |p| %>
        <li><%= link_to prescription(p), patient_appointment_path(@patient, p.appointment) %></li>
      <% end %>
    </ul>
  <% else %>
    <p class="info">No prescriptions or medications changes recorded</p>
  <% end %>
</div>

app/views/prescriptions/_table.html.erb
<% if defined? prescriptions and prescriptions %>
  <% unless prescriptions.empty? %>
    <table class="table">
      <thead>
        <tr>

        </tr>
      </thead>
      <tfoot>
        <tr>

        </tr>
      </tfoot>
      <tbody>
        <% prescriptions.each do |p| %>
          <tr>

          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="info">No prescriptions found with the current search criteria.</p>
  <% end %>
<% end %>

app/views/prescriptions/edit.html.erb
<% content_for :page_title do %>
  <h2>Edit Medication Change for <%= @patient.ident %> on <%=on_dt @appointment.start_at %></h2>
<% end %>

<%= form_for([@patient, @appointment, @prescription], 
             html: { class: 'form-horizontal' }) do |f| %>
  <%= errors_in(@prescription) %>
  <%= render partial: 'prescriptions/form', locals: { f: f }  %>
  <hr/>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
      <%= link_to 'Show', 
          [@patient, @appointment, @prescription] %> |
      <%= link_to 'Back', 
          patient_appointment_prescriptions_path(@patient, @appointment) %>
    </div>
  </div>
<% end %>

app/views/prescriptions/index.html.erb
<h1>Listing prescriptions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Patient</th>
      <th>Medication status</th>
      <th>Prescription</th>
      <th>Notes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @presenter.each do |prescription| %>
      <tr>
        <td><%= prescription.user_id %></td>
        <td><%= prescription.patient_id %></td>
        <td><%= prescription.medication_status %></td>
        <td><%= prescription.prescription %></td>
        <td><%= prescription.notes %></td>
        <td><%= link_to 'Show', [@patient, @appointment, prescription] %></td>
        <td><%= link_to 'Edit', edit_patient_appointment_prescription_path(@patient, @appointment, prescription) %></td>
        <td><%= link_to 'Destroy', [@patient, @appointment, prescription], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription', new_patient_appointment_prescription_path(@patient, @appointment) %>

app/views/prescriptions/new.html.erb
<% content_for :page_title do %>
  <h2>New Medication Change for <%= @patient.ident %> on <%=on_dt @appointment.start_at %></h2>
<% end %>

<%= form_for([@patient, @appointment, @prescription], 
             html: { class: 'form-horizontal' }) do |f| %>
  <%= errors_in(@prescription) %>
  <%= render partial: 'prescriptions/form', locals: { f: f }  %>
  <hr/>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
      <%= link_to 'Back', patient_appointment_prescriptions_path(@patient, @appointment) %>
    </div>
  </div>
<% end %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @prescription.user_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @prescription.patient_id %>
</p>

<p>
  <strong>Medication status:</strong>
  <%= @prescription.medication_status %>
</p>

<p>
  <strong>Prescription:</strong>
  <%= @prescription.prescription %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @prescription.notes %>
</p>

<%= link_to 'Edit', edit_patient_appointment_prescription_path(@patient, @appointment, @prescription) %> |
<%= link_to 'Back', patient_appointment_prescriptions_path(@patient, @appointment)  %>