config/routes.rb
Ehr::Application.routes.draw do

  resources :patients do
    resources :addresses
    resources :contacts
    resources :allergies
    resources :appointments do
      resources :progress_notes
      resources :initial_evaluations
      resources :prescriptions
      member do
        get 'cancel'
        get 'uncancel'
      end
    end
    resources :patient_doctor_relations
    collection do 
      get 'ethnicities', format: :json
      get 'occupations', format: :json
      get 'marital_statuses', format: :json
    end
  end

  resources :calendars, only: [ :index ]

  devise_for :users

  root 'home#index'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  extend ScopedSearch
  include PatientStatus
  include Gender

  belongs_to :user

  has_many :patient_doctor_relations, dependent: :destroy
  has_many :users,                    through: :patient_doctor_relations

  has_many :addresses,                dependent: :destroy
  has_many :contacts,                 dependent: :destroy
  has_many :patient_notes,            dependent: :destroy
  has_many :allergies,                dependent: :destroy
  has_many :prescriptions,            dependent: :destroy
  has_many :appointments,             dependent: :destroy
  has_many :progress_notes,           dependent: :destroy
  has_many :initial_evaluations,      dependent: :destroy

  validates :ident, :status, presence: true

  scope :by_id, ->(id) { where(id: id.to_i) if id and id.to_i > 0 }
  scope :by_ident, ->(ident) { where(ident: ident.to_s) if ident.present? }
  scope :by_dob, ->(stdt, endt) { date_range_lambda.call(stdt, endt, :dob) }
  scope :by_created_at, ->(stdt, endt) { date_range_lambda.call(stdt, endt) }
  scope :by_search, ->(q) { fields_like_lambda.call(q, [:fname, :lname, :mname]) }

  def name
    [ fname, mname, lname ].reject(&:blank?).join(' ')
  end

  def initials
    [ fname, mname, lname ].reject(&:blank?).map {|s| s[0].upcase }.join(' ')
  end   

  def last_interaction
    self.appointments.not_canceled.occurred_before.order('start_at desc').first
  end

  def last_visit
    self.appointments.
        not_canceled.
        occurred_before.
        where(appointment_type: AppointmentType::VISIT_TYPES).
        order('start_at desc').
        first
  end

  def current_and_past_appointments
    self.appointments.occurred_before.order('start_at desc')
  end

  def next_appointment limit = 1
    self.appointments.scheduled_after.not_canceled.order('start_at asc').limit(limit)
  end

  def dob_str= str
    tmp = Date.strptime(str, '%m/%d/%Y')
    self.dob = tmp
  rescue Exception => e
    errors.add(:dob, 'Date must be in MM/DD/YYYY format')
  end

  def dob_str 
    if self.dob
      self.dob.strftime('%m/%d/%Y')
    end
  end

  def prescriptions_in_order desc = true
    self.prescriptions.sort do |lhs,rhs|
      lhs_tm = lhs.appointment ? lhs.appointment.start_at : lhs.created_at
      rhs_tm = rhs.appointment ? rhs.appointment.start_at : rhs.created_at
      if desc
        rhs_tm <=> lhs_tm
      else
        lhs_tm <=> rhs_tm
      end
    end
  end

  def age
    Date.today.year - self.dob.year if self.dob
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_patient, only: [ :show, :edit, :update, :destroy ]

  def index
    @presenter = PatientsPresenter.new(current_user, params)

    respond_to do |format|
      format.html
      format.json
    end
  end

  def ethnicities
    @presenter = PatientsPresenter.new(current_user, params)
    render json: {
      options: @presenter.ethnicities
    }
  end

  def occupations
    @presenter = PatientsPresenter.new(current_user, params)
    render json: {
      options: @presenter.occupations
    }
  end

  def marital_statuses
    @presenter = PatientsPresenter.new(current_user, params)
    render json: {
      options: @presenter.marital_statuses
    }
  end

  def show
    @patient = PatientPresenter.new(current_user, @patient)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @patient = Patient.new
    @patient.user = current_user
  end

  def create
    @patient = Patient.new(create_params)
    @patient.user = current_user
    if @patient.save
      PatientDoctorRelation.create(user: current_user, patient: @patient)
      redirect_to @patient, notice: 'Patient created'
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @patient.update_attributes(update_params)
      redirect_to @patient, notice: 'Patient information successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @patient.status = PatientStatus::DELETED
    if @patient.save
      redirect_to patients_path, notice: 'Patient marked as deleted'
    else
      redirect_to patients_path, flash: { warning: 'Unable to mark the patient as deleted.' }
    end
  end

  private 

  def set_patient
    @patient = current_user.patients.find(params[:id])
  end

  def create_params
    params.require(:patient).permit(:ident, :status, :fname, :mname, :lname, :dob, :dob_str, :marital_status, :occupation, :ethnicity, :gender)
  end

  def update_params
    params.require(:patient).permit(:fname, :mname, :lname, :dob, :dob_str, :marital_status, :occupation, :ethnicity, :gender)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
  def gender_icon gender 
    if gender == Gender::FEMALE or gender == Gender::MALE_TO_FEMALE
      image_tag 'silk/female.png'
    elsif gender == Gender::MALE or gender == Gender::FEMALE_TO_MALE
      image_tag 'silk/male.png'
    end
  end

  def patient_title patient
    str = "#{ patient.name }, #{ patient.long_gender }"
    str << ", #{ patient.age } y.o." if patient.age
    str
  end
end

app/views/patients/_form.html.erb
  <div class="control-group required">
    <%= f.label :ident, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :ident, length: 6, class: 'span3' %>
    </div>
  </div>
  <div class="control-group required">
    <%= f.label :status, class: 'control-label' %>
    <div class="controls">
      <%= f.select :status, PatientStatus::ALL_STATUS, { include_blank: true }, class: 'span3' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :fname, 'Name', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :fname, placeholder: 'First', class: 'span3' %>
      <%= f.text_field :mname, placeholder: 'Middle', class: 'span2' %>
      <%= f.text_field :lname, placeholder: 'Last', class: 'span3' %>
    </div>
  </div>    
  <div class="control-group">
    <%= f.label :gender, 'Gender', class: 'control-label' %>
    <div class="controls">
      <%= f.select :gender, Gender::ALL_GENDER_FOR_SELECT, { include_blank: true }, class: 'span3' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dob, 'Date of Birth', class: 'control-label' %>
    <div class="controls">
      <%= date_input f, :dob_str %>
    </div>
  </div>
  <%= javascript_tag do %>
    $(function() {
      var dt = $('.dob_str-picker').datetimepicker({
          language: 'en',
          pickTime: false });
    });
  <% end %>
  <div class="control-group">
    <%= f.label :marital_status, 'Marital Status', class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :marital_status, class: 'span4', autocomplete: 'off' %>
    </div>
    <%= javascript_tag do %>
      $(function() {
        $('#patient_marital_status').typeahead({
          source: function(query, process) {
            return $.get('<%= marital_statuses_patients_path %>', { query: query }, function(data) {
              return process(data.options)
            });
          }
        });
      });
    <% end %>
  </div>
  <div class="control-group">
    <%= f.label :ethnicity, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :ethnicity, autocomplete: 'off', class: 'span4' %>
    </div>
    <%= javascript_tag do %>
      $(function() {
        $('#patient_ethnicity').typeahead({
          source: function(query, process) {
            return $.get('<%= ethnicities_patients_path %>', { query: query }, function(data) {
              return process(data.options)
            });
          }
        });
      });
    <% end %>
  </div>
  <div class="control-group">
    <%= f.label :occupation, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :occupation, class: 'span4', autocomplete: 'off' %>
    </div>
    <%= javascript_tag do %>
      $(function() {
        $('#patient_occupation').typeahead({
          source: function(query, process) {
            return $.get('<%= occupations_patients_path %>', { query: query }, function(data) {
              return process(data.options)
            });
          }
        });
      });
    <% end %>
  </div>

app/views/patients/_sidebar.html.erb
<div class="module-block">
  <div id="calendar"></div>
  <%= javascript_tag do %>
    $(document).ready(function() {    
      $.get('<%= patient_appointments_path(@patient) %>', {}, function(data) {
        var today = new Date();
        var dt = new Date(today.getFullYear(), 
            today.getMonth() - 2, 
            today.getDate());
        calendarViz.buildMonth(dt, data);
      }, 'json');
    });
  <% end %>
</div>

<%= render partial: 'allergies/module' %>
<%= render partial: 'prescriptions/module' %>
<%= render partial: 'contacts/sidebar' %>
<%= render partial: 'addresses/sidebar' %>

app/views/patients/_summary.html.erb
<% if defined? patient and patient %>
  <div class="patient-summary" id="<%= patient.ident %>">
    <h5><%= link_to patient_title(patient), patient %> 
      <div class="actions">
        <%= link_to 'Edit Patient', edit_patient_path(p), class: 'bullet-edit' %>
        <%= link_to 'Add Appointment', new_patient_appointment_path(p), 
            class: 'bullet-appointment' %>
      </div>
    </h5>
  </div>
<% end %>

app/views/patients/_table.html.erb
<% if defined? patients and patients %>
  <% if patients.count > 0 %>
    <%= form_tag(nil, { method: 'get'}) do %>
    <table class="table">
      <thead>
        <tr>
          <th>Ident</th>
          <th>Name</th>
          <th>&nbsp;</th>
          <th>DOB</th>
          <th>Last</th>
          <th>Scheduled</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td colspan="7"><%= paginate patients.collection %></td>
        </tr>
      </tfoot>
      <tbody>
        <% patients.each do |p| %>
          <tr>
            <td><%= link_to p.ident, patient_path(p) %></td>
            <td><%= p.name %></td>
            <td><%= gender_icon p.gender %></td>
            <td><%= p.dob_str %></td>
            <td><%= appointment(p.last_interaction, false) %></td>
            <td><%= appointment(p.next_appointment.first, false) %></td>
            <td class="actions">
              <%= link_to 'Edit Patient', edit_patient_path(p), 
                  class: 'bullet-edit' %>
              <%= link_to 'Add Appointment', new_patient_appointment_path(p), 
                  class: 'bullet-appointment' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  <% else %>
    <p class="info">No patients were found with the current search criteria.</p>
  <% end %>
<% end %>

app/views/patients/edit.html.erb
<%= form_for @patient, html: { class: 'form-horizontal' } do |f| %>
  <%= errors_in @patient %>
  <%= render partial: 'patients/form', locals: { f: f } %>
  <hr/>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %> 
      <%= link_to 'Show', @patient %>
      <%= link_to 'Back', patients_path %>
    </div>
  </div>
<% end %>

app/views/patients/index.html.erb
<% content_for :page_title do %>
  <h2>Patient List</h2>
<% end %>

<% content_for :actions do %>
  <div class="action-block">
    <%= link_to 'Add New Patient to Database', new_patient_path, class: 'med-icon-link med-patient' %>
  </div>
<% end %>

<%= render partial: 'patients/table', locals: { patients: @presenter } %>

app/views/patients/new.html.erb
<% content_for :page_title do %>
  <h2>New Patient</h2>
<% end %>

<%= form_for @patient, html: { class: 'form-horizontal' } do |f| %>
  <%= errors_in @patient %>
  <%= render partial: 'patients/form', locals: { f: f } %>
  <hr/>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %> 
      <%= link_to 'Back', patients_path %>
    </div>
  </div>
<% end %>

app/views/patients/show.html.erb
<% content_for :page_title do %>
  <h2><%= patient_title(@patient) %></h2>
<% end %>

<% content_for :actions do %>
  <div class="action-block">
    <%= link_to 'Add Appointment to Calendar', new_patient_appointment_path(@patient), class: 'med-icon-link med-calendar'  %>
    <%= link_to 'Enter New Allergy', new_patient_allergy_path(@patient), class: 'med-icon-link med-allergy' %>
  </div>
<% end %>

<% content_for :quick_look do %>
  <%= render partial: 'patients/sidebar' %>
<% end %>

<% if @patient.appointments.occurred_before.count > 0 %>
  <% @patient.appointments.occurred_before.order('start_at desc').each do |a| %>
    <%= render partial: 'appointments/display', locals: { appointment: a } %>
  <% end %>
<% end %>

<% if @patient.appointments.scheduled_after.count > 0 %>
  <h5 class="sep">Upcoming Appointments</h5>
  <% @patient.appointments.scheduled_after.order('start_at asc').each do |a| %>
    <%= render partial: 'appointments/display', locals: { appointment: a } %>
  <% end %>
<% end %>