config/routes.rb
Ehr::Application.routes.draw do

  resources :patients do
    resources :addresses
    resources :contacts
    resources :allergies
    resources :appointments do
      resources :progress_notes
      resources :initial_evaluations
      resources :prescriptions
      member do
        get 'cancel'
        get 'uncancel'
      end
    end
    resources :patient_doctor_relations
    collection do 
      get 'ethnicities', format: :json
      get 'occupations', format: :json
      get 'marital_statuses', format: :json
    end
  end

  resources :calendars, only: [ :index ]

  devise_for :users

  root 'home#index'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  extend ScopedSearch

  belongs_to :patient
  belongs_to :user

  validates :patient_id, :user_id, presence: true

  scope :by_user, ->(user_id) { where(user_id: user_id) if user_id }
  scope :by_patient, ->(patient_id) { where(patient_id: patient_id) if patient_id }
  scope :by_allowed_user, ->(user) { allowed_user_lambda.call(user) }
  scope :by_created_at, ->(stdt, endt) { date_range_lambda.call(stdt, endt) }
  scope :by_search, ->(q) { fields_like_lambda.call(q, :medication_or_food) }

end

app/controllers/allergies_controller.rb
class AllergiesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_allergy, only: [:show]
  before_action :set_writable_allergy, only: [:edit, :update, :destroy]
  before_action :set_patient

  def index
    @presenter = AllergiesPresenter.new(current_user, params)
  end

  def show
  end

  def new
    @allergy = Allergy.new
    @allergy.user = current_user
    @allergy.patient = @patient
  end

  def edit
  end

  def create
    @allergy = Allergy.new(allergy_params)
    @allergy.user = current_user
    @allergy.patient = @patient
    respond_to do |format|
      if @allergy.save
        format.html { redirect_to @patient, notice: 'Allergy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @allergy }
      else
        format.html { render action: 'new' }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @allergy.update(allergy_params)
        format.html { redirect_to @patient, notice: 'Allergy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @allergy.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @allergy.destroy
    respond_to do |format|
      format.html { redirect_to patient_url(@patient) }
      format.json { head :no_content }
    end
  end

  private

  def set_allergy
    @allergy = Allergy.by_allowed_user(current_user).find(params[:id])
  end

  def set_writable_allergy
    @allergy = current_user.allergies.find(params[:id])
  end

  def allergy_params
    params.require(:allergy).permit(:medication_or_food, :reaction)
  end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/views/allergies/_form.html.erb
  <div class="control-group">
    <%= f.label :medication_or_food, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :medication_or_food, class: 'input-block-level' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reaction, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :reaction, class: 'input-block-level' %>
    </div>
  </div>

app/views/allergies/_module.html.erb
<div class="module-block">
  <h5>Allergies</h5>
  <% unless @patient.allergies.empty? %>
    <ul>
    <% @patient.allergies.order('created_at desc').each do |a| %>
      <li><span class="allergy"><%= a.medication_or_food %></span></li>
    <% end %>
    </ul>
  <% else %>
    <p class="info">No allergies recorded.</p>
  <% end %>
</div>

app/views/allergies/_table.html.erb
<% if defined? allergies and allergies %>
  <% unless allergies.empty? %>
    <table class="table">
      <thead>
        <tr>

        </tr>
      </thead>
      <tfoot>
        <tr>

        </tr>
      </tfoot>
      <tbody>
        <% allergies.each do |a| %>
          <tr>

          </tr>
        <% end >
      </tbody>
    </table>
  <% else %>
    <p class="info">Unable to find any allergies with the current search criteria.</p>
  <% end %>
<% end %>

app/views/allergies/edit.html.erb
<% content_for :page_title do %>
  <h2>Edit Allergy for <%= @patient.ident %></h2>
<% end %>

<%= form_for([@patient, @allergy], html: { class: 'form-horizontal' }) do |f| %>
  <%= errors_in @allergy %>
  <%= render partial: 'allergies/form', locals: { f: f } %>
  <hr/>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
      <%= link_to 'Show', [@patient, @allergy] %> |
      <%= link_to 'Back', patient_allergies_path(@patient) %>
  </div>
<% end %>

app/views/allergies/index.html.erb
<h1>Listing allergies</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Patient</th>
      <th>Medication or food</th>
      <th>Reaction</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @presenter.each do |allergy| %>
      <tr>
        <td><%= allergy.user_id %></td>
        <td><%= allergy.patient_id %></td>
        <td><%= allergy.medication_or_food %></td>
        <td><%= allergy.reaction %></td>
        <td><%= link_to 'Show', [@patient, allergy] %></td>
        <td><%= link_to 'Edit', edit_patient_allergy_path(@patient, allergy) %></td>
        <td><%= link_to 'Destroy', [@patient, allergy], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Allergy', new_patient_allergy_path %>

app/views/allergies/new.html.erb
<% content_for :page_title do %>
  <h2>New Allergy for <%= @patient.ident %></h2>
<% end %>

<%= form_for([@patient, @allergy], html: { class: 'form-horizontal' }) do |f| %>
  <%= errors_in @allergy %>
  <%= render partial: 'allergies/form', locals: { f: f } %>
  <hr/>
  <div class="control-group">
    <div class="controls">
      <%= f.submit %>
      <%= link_to 'Back', patient_allergies_path(@patient) %>
  </div>
<% end %>

app/views/allergies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @allergy.user_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @allergy.patient_id %>
</p>

<p>
  <strong>Medication or food:</strong>
  <%= @allergy.medication_or_food %>
</p>

<p>
  <strong>Reaction:</strong>
  <%= @allergy.reaction %>
</p>

<%= link_to 'Edit', edit_patient_allergy_path(@patient, @allergy) %> |
<%= link_to 'Back', patient_allergies_path(@patient) %>